name: Format code

on:
  push:
    branches: [ "utexo-master", "dev", "stage", "master" ]
  pull_request:
    branches: [ "utexo-master", "dev", "stage", "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Authenticate to private RGB forks
        shell: bash
        run: |
          git config --global \
            url."https://x-access-token:${{ secrets.BFA_MIRRORS_TOKEN }}@github.com/UTEXO-Protocol/".insteadOf \
            "https://github.com/UTEXO-Protocol/"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Format
        run: cargo fmt --all -- --check --config format_code_in_doc_comments=true
      - name: Format c-ffi bindings
        working-directory: ./bindings/c-ffi
        run: |
          make format
          git diff --exit-code
      - name: Format uniffi bindings
        working-directory: ./bindings/uniffi
        run: cargo fmt -- --check
